apiVersion: v1
kind: Namespace
metadata:
  name: network-ranger

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: network-ranger
  name: network-ranger
  labels:
    app: network-ranger

spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-ranger
  template:
    metadata:
      labels:
        app: network-ranger
    spec:
      containers:
        - name: network-ranger
          image: ghcr.io/disnog/netranger-bot:latest
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: TOKEN
            - name: GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: GUILD_ID
            - name: BOT_DESCRIPTION
              value: "Network Ranger"
            - name: WELCOMECHANNEL_NAME
              value: "welcome"
            - name: MEMBERCHANNEL_NAME
              value: "general"
            - name: LOGCHANNEL_NAME
              value: "cnc"
            - name: MIRRORCHANNEL_NAME
              value: "mirror"
            - name: MEMBERROLE_NAME
              value: "Members"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: DB_HOST
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: DB_PASS
            - name: DB_NAME
              value: "netranger"
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_SERVER
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_PASSWORD
            - name: SMTP_FROMEMAIL
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_FROMEMAIL
            - name: SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SECRETKEY
