apiVersion: v1
kind: Namespace
metadata:
  name: network-ranger

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: network-ranger
  name: network-ranger
  labels:
    app: network-ranger

spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-ranger
  template:
    metadata:
      labels:
        app: network-ranger
    spec:
      containers:
        - name: network-ranger
          image: netdiscord/network-ranger:latest
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: TOKEN
            - name: BOT_DESCRIPTION
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: BOT_DESCRIPTION
            - name: COMMAND_PREFIX
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: COMMAND_PREFIX
            - name: LOGCHANNEL_NAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: LOGCHANNEL_NAME
            - name: MEMBERCHANNEL_NAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: MEMBERCHANNEL_NAME
            - name: MEMBERROLE_NAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: MEMBERROLE_NAME
            - name: EGGSROLE_NAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: EGGSROLE_NAME
            - name: WELCOMECHANNEL_NAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: WELCOMECHANNEL_NAME
            - name: GUILD_NAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: GUILD_NAME
            - name: MIRRORCHANNEL_NAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: MIRRORCHANNEL_NAME
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_PASSWORD
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_SERVER
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_PORT
            - name: SMTP_FROMEMAIL
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SMTP_FROMEMAIL
            - name: SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SECRETKEY
            - name: DB_HOST
              value: "mongodb"
            - name: DB_PORT
              value: "27017"
            - name: DB_USER
              value: "root"
            - name: DB_NAME
              value: "network_ranger"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
