name: Docker Image CI

on:
  push:
    branches: [ master next ]
  pull_request:
    branches: [ master next ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag netdiscord/network-ranger:$(date +%s)
